const { chromium } = require('C:/Users/willion/.workbuddy/binaries/node/workspace/node_modules/playwright-core');
const CHROME = 'C:/Users/willion/.agent-browser/browsers/chrome-152.0.7977.64/chrome.exe';
const APP = 'http://127.0.0.1:8899/purelab-apk/app/assets/www/index.html';
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: CHROME });
  const page = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
  page.on('pageerror', e => console.log('PAGEERROR:', String(e).slice(0, 300)));
  await page.goto(APP, { waitUntil: 'load' });
  await page.evaluate(() => localStorage.clear());
  await page.reload({ waitUntil: 'load' });
  await page.waitForTimeout(400);
  const go = async a => page.evaluate(a => { const el = [].find.call(document.querySelectorAll('[data-go="' + a + '"]'), e => e.getClientRects().length > 0); if (el) { el.click(); return true; } return false; }, a);
  const wait = (ms = 300) => page.waitForTimeout(ms);
  const screen = () => page.evaluate(() => [].filter.call(document.querySelectorAll('.screen'), s => getComputedStyle(s).display !== 'none')[0].id);
  await go('s02'); await wait(500);
  console.log('start:', await screen());
  await page.evaluate(() => document.querySelector('#exp-carousel [data-delexp="EXP-01"]').click()); await wait(250);
  console.log('after del-click EXP-01:', await screen());
  await page.evaluate(() => document.getElementById('delexp-go').click()); await wait(350);
  console.log('after confirm EXP-01:', await screen());
  await page.evaluate(() => document.querySelector('#exp-carousel [data-delexp="EXP-03"]').click()); await wait(250);
  console.log('after del-click EXP-03:', await screen());
  await page.evaluate(() => document.getElementById('delexp-go').click()); await wait(350);
  console.log('after confirm EXP-03:', await screen());
  await browser.close();
})();
